name: wra5
description: A simple Flutter app with Whalyze features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  heroicons: ^0.11.0
  file_picker: ^8.0.0+1
  receive_sharing_intent: ^1.8.1
  google_fonts: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/privacidad.png
    - assets/images/fondo-back.png
    - assets/images/saludo_home.png

